name: "Resume CI"

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      build:
        description: "build"
        required: false
        default: "false"

permissions: 
  actions: read
  checks: read
  contents: read
  deployments: read
  issues: read
  pull-requests: read
  repository-projects: write
  security-events: read

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      have_build: ${{ steps.have_build.outputs.result }}
    steps:
      - name: Build new Image or not
        id: have_build
        run: |
          BUILD="${{ github.event.inputs.build }}"
          BUILD="${BUILD:-false}"

          COMMIT_MSG="${{ github.event.head_commit.message }}"
          COMMIT_MSG="$(echo $COMMIT_MSG | awk '{print tolower($0)}')"

          VERDICT=true
          if [[ ! "$COMMIT_MSG" =~ ^build.* ]] && [[ "$BUILD" != "true" ]]; then
            echo "Commit not start with 'build' or input is false"
            VERDICT=false
          fi

          echo "::set-output name=result::$VERDICT"

  validate:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate resume
        run: ./bin/resume --validate resume.yaml

      - name: Notify to server
        if: needs.prepare.outputs.have_build == 'false'
        run: |
          TOKEN="${{ secrets.GITHUB_TOKEN }}"
          CODE=$(curl -sSLf -H "Authorization: token $TOKEN" -w "%{http_code}" https://resume.anhdv.dev/fetch)
          [[ "$CODE" == 20* ]] || exit 1

  build:
    needs:
      - prepare
      - validate
    if: needs.prepare.outputs.have_build == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Validate resume
        run: ./bin/resume --validate resume.yaml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/resume:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  deploy:
    needs:
      - prepare
      - build
    if: needs.prepare.outputs.have_build == 'true'
    runs-on: ubuntu-18.04
    steps:
      - name: Install SSH Key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: sudo service resume restart
